# Generated by Django 4.2.2 on 2023-09-07 20:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('username', models.CharField(error_messages={'unique': 'This username is already in use. Please choose another.'}, max_length=30, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Please enter a valid email', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')], verbose_name='E-mail')),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='The password must have at least 8 characters.', regex='^.{8,}$')], verbose_name='Password')),
                ('password_confirmation', models.CharField(max_length=128, verbose_name='Password Confirmation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
