# Generated by Django 4.2.2 on 2023-12-14 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_authors_user'),
        ('recipes', '0003_alter_recipe_cover_alter_recipe_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.authors'),
        ),
    ]
